/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPort
#define _Included_android_serialport_api_SerialPort


/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
extern "C" JNIEXPORT jobject JNICALL Java_com_xmlenz_lzcan_LZCan_SerialPortOpen(JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_xmlenz_lzcan_LZCan_SerialPortClose(JNIEnv *, jobject);



extern "C"
JNIEXPORT jobjectArray JNICALL
Java_com_xmlenz_lzcan_LZCan_getCanRawArray(JNIEnv *env, jobject thiz, jint n_can);


extern "C"
JNIEXPORT void JNICALL
Java_com_xmlenz_lzcan_LZCan_closeCan(JNIEnv *env, jobject thiz, jint n_can) ;

extern "C"
JNIEXPORT void JNICALL
Java_com_xmlenz_lzcan_LZCan_beep(JNIEnv *env, jobject thiz);

extern "C"
JNIEXPORT void JNICALL
Java_com_xmlenz_lzcan_LZCan_sendCmdCan(JNIEnv *env, jobject thiz, jint n_can, jint canid, jbyteArray data) ;

extern "C"
JNIEXPORT void JNICALL
Java_com_xmlenz_lzcan_LZCan_sendCmdCans(JNIEnv *env, jobject thiz, jint n_can, jint canid,
                                        jint cmd_number, jbyteArray data);


#endif
